version: "3"
services:
    frontend:
        image: kuhoo2000/docker-frontend
        volumes:
            - /app/node_modules
            - ./frontend:/app
        stdin_open: true
        mem_limit: 128m

    nginx:
        restart: always
        image: kuhoo2000/docker-nginx
        ports:
            - "80:80"

    # backend:
    #   image: johnahn/docker-backend
    #   container_name: app_backend
    #   volumes:
    #     - /app/node_modules
    #     - ./backend:/app
    #   mem_limit: 128m
    #   environment:
    #     MYSQL_HOST: $MYSQL_HOST
    #     MYSQL_USER: $MYSQL_USER
    #     MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    #     MYSQL_DATABASE: $MYSQL_DATABASE
    #     MYSQL_PORT: $MYSQL_PORT

    # backend:
    #     build:
    #         dockerfile: Dockerfile.dev
    #         context: ./backend
    #     container_name: app_backend
    #     volumes:
    #         - /app/node_modules
    #         - ./backend:/app
    #     environment:
    #         MYSQL_HOST: mysql
    #         MYSQL_USER: root
    #         MYSQL_ROOT_PASSWORD: 12345678
    #         MYSQL_DATABASE: myapp
    #         MYSQL_PORT: 3306

    # mysql:
    #     build: ./mysql
    #     restart: unless-stopped
    #     container_name: app_mysql
    #     ports:
    #         - "3306:3306"
    #     volumes:
    #         - ./mysql/mysql_data:/var/lib/mysql
    #         - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    #     environment:
    #         MYSQL_ROOT_PASSWORD: 12345678
    #         MYSQL_DATABASE: myapp
    #
